run:
  deadline: 10m10s

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - funlen
    - goerr113
    - gocognit
    - gomnd
    - lll
    - wsl
    - gochecknoglobals
