---
name: GoLang Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

env:
  GO_VERSION: "1.17"

concurrency:
  group: 'golint-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: golangci/golangci-lint-action@v2
        with:
          args: -v
