---
name: Release
on:
  push:
    tags:
      - "v*"

env:
  GO_VERSION: "1.17"
  GH_USER: "tmeckel"

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
