---
name: Validate Dockerfile
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**/Dockerfile'

env:
  GO_VERSION: "1.17"

jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: make docker-scan
